### PR TITLE
[HOPSWORKS-1418] upgrade pytorch and examples to 1.3.1 and add a tensorboard example

### PR DESCRIPTION
**Pull request by jimdowling**
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1418

### CODE REVIEW

**Comment by robzor92** [comment]
This one also: https://github.com/logicalclocks/hops-examples/blob/master/notebooks/featurestore/petastorm/PetastormMNIST_PyTorch.ipynb

**Comment by jimdowling** [comment]
@robzor92 I tried to run it, but you have to have the petastorm training dataset, which isn't part of the featurestore tour anymore. I don't see any breaking changes in the code,  so i suggest skipping it for now.

**Comment by jimdowling** [comment]
Looks like i overwrote the differential evolution notebook with the experiment one. Will fix tomorrow.

**Comment by robzor92** [comment]
Okay then we can skip the pytorch example for now.

**Pull request merged**
