### PR TITLE
[HOPSWORKS-906] Use experiments service in feature store tour

### PR DESCRIPTION
**Pull request by Limmen**
- Demonstrate how feature store can be integrated with Experiments service in the tour examples

### CODE REVIEW

**Comment by Limmen** [comment]
@robzor92 @tkakantousis , refactored code examples to use experiments service when training on a training_dataset in the feature store.

**Comment by Limmen** [comment]
> Does the python example support both 2.7 and 3.6? Would be nice to test it out on a VM. Also since it uses evolutionary search it is important to make sure it does not generate a ton of files in the Experiments dataset.

Good point, I forgot that, will try python 2.7 now. Regarding evo-search, I think it should be okey it only runs for 1 generation with small population and uses local_logdir=True. Or is there some more setting I can use to minimize output?

**Comment by robzor92** [comment]
Okay given it is only 1 generation and 4 population should not be a problem. local_logdir=True actually only means that tensorboard.logdir() ends up in the $CWD/tensorboard_logdir folder of your spark executor. So that APIs which do not support HDFS can "write" to HDFS since the contents of tensorboard_logdir folder gets uploaded to the Experiments dataset after the particular experiment is finished. It does not reduce the number of files (it becomes an intermediary directory). local_logdir=False means we point directly to the path in HDFS (in the experiments dataset) which is nice for example for TF/Keras. For example if the code checkpoints the model it can be removed, although since it is so few runs it should be fine.

**Comment by robzor92** [comment]
Also, if the example supports writing to HDFS then it should be local_logdir=True. Can you try it? Otherwise local_logdir=False is the only option. If local_logdir=True then the TensorBoard in Experiments service will show events while training. As opposed to only after when local_logdir=False since files are uploaded at the end then.

**Comment by Limmen** [comment]
> Also, if the example supports writing to HDFS then it should be local_logdir=True. Can you try it? Otherwise local_logdir=False is the only option. If local_logdir=True then the TensorBoard in Experiments service will show events while training. As opposed to only after when local_logdir=False since files are uploaded at the end then.

Ah okay, now I get it. I will add the flag "save_best_only" to checkpoiniting to reduce the number of files also. Will try local_logdir=False

**Comment by Limmen** [comment]
@robzor92 Tested with python 2 now. Also updated to reduce checkpoint files

**Pull request merged**
