### PR TITLE
[HOPSWORKS-1978] schematized tags

### PR DESCRIPTION
**Pull request by o-alex**
updating hsfs examples that show tag usage

### CODE REVIEW

**Review by jimdowling — CHANGES_REQUESTED** [review]
Can you write a new notebook in hsfs called 'feature-engineering-with-tags'?
Rather than make the introductory notebook more complex, please add a new one, so that developers can start with the simplest notebook, then find a new one that adds tagging.

**Comment by jimdowling** [comment]
Same for the training datasets notebook. 
Actually, create a subdirectory in hsfs called 'tagging' and put your 2 notebooks there.

**Comment by o-alex** [comment]
I moved all the tags code into one `feature_store_tags.ipynb` notebook. I didn't duplicate it into 2 notebooks - feature group and training dataset, because in most of the notebook I show how to attach tags and what the values can be. There is a small section on how to attach tags to training datasets where i basically show that the API calls are identical to fg.

**Review by SirOibaf — CHANGES_REQUESTED** [review]
Oh c'mon it's always the same. Examples are here to a) show users how to use the platform and b) give users ideas on how to best use the platform. 

Please tell me, what can someone understand with this example:
```
tag4_value_1={}
tag4_value_1['f']='test'
tag4_value_2={}
tag4_value_2['f']='not'
tag4_value=[tag4_value_1, tag4_value_2]
fg_read.add_tag(tag4_name, tag4_value)
```
Leaving aside the fact that you don't need 2 lines to define a python dictionary with a single key. is it that hard to pick some meaningful english words and build a proper example which doesn't have abbreviations/numbers everywhere and tell the user a story that conveys how to use the platform and best practices?

Also you need the markdown metadata on top for the new examples.hopsworks.ai

Also, as for the documentation, please take the screenshots from the new ui.

**Review by SirOibaf — APPROVED** [review]

**Pull request merged**
